# Generated by Django 4.2.7 on 2025-07-06 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('email', 'Email'), ('calendar', 'Calendar'), ('notes', 'Notes'), ('meeting', 'Meeting'), ('chat', 'Chat/Message'), ('document', 'Document'), ('voice', 'Voice Input'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_keywords', models.JSONField(blank=True, default=list)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('urgency_indicators', models.JSONField(blank=True, default=list)),
                ('deadline_mentions', models.JSONField(blank=True, default=list)),
                ('processed_insights', models.JSONField(blank=True, default=dict)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Context Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_enhanced', models.BooleanField(default=False)),
                ('ai_enhanced_description', models.TextField(blank=True)),
                ('ai_estimated_duration', models.CharField(blank=True, max_length=50)),
                ('ai_suggested_deadline', models.DateTimeField(blank=True, null=True)),
                ('priority_score', models.FloatField(default=0.5)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category')),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskContextRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_relations', to='tasks.contextentry')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_relations', to='tasks.task')),
            ],
            options={
                'ordering': ['-relevance_score'],
                'unique_together': {('task', 'context_entry')},
            },
        ),
    ]
